### ISSUE TITLE
not a issue, question 

### ISSUE THREAD

**Issue by LearningFTW** [codewars/cobol-test#1]
> The period cannot appear in any literal (even inside quotes). The maximum test case title length is 80 characters.

I'm assuming this `testcase "fixed tests for n = 9.2, x = 5 and a = 1"` or any other similar decimal based would not be possible ? (or I read the entire para wrong)

**Comment by monadius** [comment]
You are correct: it is not possible. The current preprocessor is very primitive. But it will be not difficult to improve it later.

**Comment by LearningFTW** [comment]
Ok. thanks.

Also thanks for creating this
